export const ActionTypes =  {
  WEBSOCKET_CONNECT: "WEBSOCKET_CONNECT",
  WEBSOCKET_DISCONNECT: "WEBSOCKET_DISCONNECT",
  WEBSOCKET_SEND: "WEBSOCKET_SEND",
  WEBSOCKET_CONNECTING: "WEBSOCKET_CONNECTING",
  WEBSOCKET_CONNECTED: "WEBSOCKET_CONNECTED",
  WEBSOCKET_DISCONNECTED: "WEBSOCKET_DISCONNECTED",
  WEBSOCKET_MSG_ERROR: "WEBSOCKET_MSG_ERROR",

  ARTIST_SUBSCRIBE: "ARTIST_SUBSCRIBE",
  ARTIST_UNSUBSCRIBE: "ARTIST_UNSUBSCRIBE",
  ARTIST_ADDED: "ARTIST_ADDED",
  ARTIST_DELETED: "ARTIST_DELETED",
  ARTIST_UPDATED: "ARTIST_UPDATED",

  ALBUM_SUBSCRIBE: "ALBUM_SUBSCRIBE",
  ALBUM_UNSUBSCRIBE: "ALBUM_UNSUBSCRIBE",

  SONG_UPDATE: "SONG_UPDATE",
  SONG_DELETE_CONFIRM: "SONG_DELETE_CONFIRM",
  SONG_DELETE: "SONG_DELETE",
  
  SONG_ADDED: "SONG_ADDED",
  SONG_UPDATED: "SONG_UPDATED",
  SONG_DELETED: "SONG_DELETED",
  SONG_UPDATE_ERR: "SONG_UPDATE_ERR",

  FETCH_GENRES: "FETCH_GENRES",
  GENRE: "GENRE", 

  NOTIFY_CLOSE: "NOTIFY_CLOSE",
  CONFIRM: "CONFIRM",
  CONFIRM_CLOSE: "CONFIRM_CLOSE",
}

export default ActionTypes;

export const NotifyStatuses = {
  DEFAULT: "DEFAULT",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
}